changes

diff --git a/bulkrename b/bulkrename
--- a/bulkrename
+++ b/bulkrename
@@ -2,101 +2,134 @@
 # bulkrename: bulk rename files using $EDITOR and temporary files
 # this file in public domain
 
-set -f -e -u
+EDITOR="${EDITOR:-"${VISUAL:-"vi"}"}"
 
-EDITOR="${EDITOR:-${VISUAL:-vi}}"
-
-usage()
-{
-	echo "usage: bulkrename [file...]" >&2
+# create temporary files
+if ! tmpfile="$(mktemp)"
+then
+	printf "bulkrename: could not make temporary file\n" >&2
 	exit 1
-}
+fi
+trap 'rm -f "$tmpfile"' EXIT
 
-# quote and escape filename for moving
-quote()
-{
-	echo "$1" | sed "s/'/'\\\\''/g; s/^/'/; s/\$/'/"
-}
-
-# populate the files $old and $new with filenames, one per line
-populatefiles()
-{
-	if [ $# -eq 0 ]
-	then                            # run on stdin
-		cat | tee "$old" > "$new"
-	else                            # run on arguments
-		for i
-		do
-			printf "%s\n" "$i" >> "$old"
-			printf "%s\n" "$i" >> "$new"
-		done
-	fi
-}
-
-# edit the filenames in $new and test if they are valid
-editfile()
-{
-	if [ "$(wc -l <"$old")" -ne "$(sort -u "$old" | wc -l)" ]
-	then
-		echo "bulkrename: repeated filenames to be renamed" >&2
-		exit 1
-	fi
-
-	"$EDITOR" "$new" </dev/tty
-
-	if [ $(wc -l <"$new") -ne $(wc -l <"$old") ]
-	then
-		echo "bulkrename: number of filenames not equal to number of files" >&2
-		exit 1
-	fi
-
-	if [ "$(wc -l <"$new")" -ne "$(sort -u "$new" | wc -l)" ]
-	then
-		echo "bulkrename: repeated target filenames" >&2
-		exit 1
-	fi
-}
-
-# create $cmd file
-createcmd()
-{
-	cat /dev/null >"$cmd"
-	while read -r from <&3 && read -r to <&4
+# if no argument is passed, fill $@ with lines from stdin
+if [ $# -eq 0 ]
+then                            # run on stdin
+	while read -r line
 	do
-		if [ "$from" != "$to" ]
-		then
-			from=$(quote "$from")
-			to=$(quote "$to")
-			printf "mv %s\t%s\n" "$from" "$to" >> "$cmd"
-		fi
-	done 3<"$old" 4<"$new"
-}
+		set -- "$@" "$line"
+	done
+fi
 
-# remove temporary files
-cleanup()
-{
-	rm -f "$old" "$new" "$cmd"
-}
-
-while getopts 'h' c
+# check if arguments are valid and write them to tmpfile
+nargs="$#"
+for arg
 do
-	case "$c" in
-	h|*)
-		usage
+	case "$arg" in
+	("")
+		printf "bulkrename: empty argument\n" >&2
+		exit 1
+		;;
+	(*[[:cntrl:]]*)
+		printf "bulkrename: control characters in filenames are not supported\n" >&2
+		exit 1
+		;;
+	([[:space:]]*|*[[:space:]])
+		printf "bulkrename: filenames beginning or ending in space is not supported\n" >&2
+		exit 1
+		;;
+	esac
+	if ! test -e "$arg"
+	then
+		printf "bulkrename: %s: file does not exist\n" "$arg" >&2
+		exit 1
+	fi
+	printf "%s\n" "$arg" >> "$tmpfile"
+done
+
+# call editor on tmpfile
+"$EDITOR" -- "$tmpfile" </dev/tty
+
+# read new filenames from edited tmpfile
+while read -r target && test "$nargs" -gt 0
+do
+	source="$1"
+
+	# for each target filename read from the file there is a
+	# corresponding entry in $@.  We read filenames from the
+	# file up to $nargs, and append $@ with commands:
+	# "rm" "file"           (remove file)
+	# "mv0" "from" "to"     (move file on the next loop)
+	# "mv1" "from" "to"     (move file on the last loop)
+	if test -z "$target"
+	then
+		# line asks to remove file
+		set -- "$@" "rm" "$source"
+	elif test "$target" = "$source"
+	then
+		# line does nothing
+		:
+	elif i=0 && for arg ; do test "$((i++))" -lt "$nargs" && test "$target" = "$arg" && break ; done
+	then
+		# line renaming creates filename collision; get unique filename
+		unique="$source"
+		while test -e "$unique"
+		do
+			unique="$unique~"
+		done
+		set -- "$@" "mv0" "$source" "$unique"
+		set -- "$@" "mv1"  "$unique" "$target"
+	else
+		# line is a renaming without collision
+		set -- "$@" "mv0" "$source" "$target"
+	fi
+
+	# we're done with this source file
+	shift
+	nargs="$((nargs - 1))"
+done <"$tmpfile"
+shift "$nargs"
+
+# perform the commands specified in the argument list
+while test "$#" -gt 0
+do
+	case "$1" in
+	("rm")
+		rm -- "$2"
+		printf "rm %s\n" "$2"
+		shift 2
+		;;
+	("mv0")
+		mv -- "$2" "$3"
+		printf "%s -> %s\n" "$2" "$3"
+		shift 3
+		;;
+	("mv1")
+		set -- "$@" "mv2" "$2" "$3"
+		shift 3
+		;;
+	("mv2")
+		break
+		;;
+	(*)
+		printf "bulkrename: unknown command %s\n" "$1" >&2
+		exit 1
 		;;
 	esac
 done
-shift $((OPTIND -1))
 
-old=$(mktemp)
-new=$(mktemp)
-cmd=$(mktemp)
-
-trap cleanup EXIT
-
-populatefiles "$@"
-editfile
-createcmd
-sh -x "$cmd"
-
-exit 0
+# perform the commands specified in the argument list (the final ones)
+while test "$#" -gt 0
+do
+	case "$1" in
+	("mv2")
+		mv -- "$2" "$3"
+		printf "%s -> %s\n" "$2" "$3"
+		shift 3
+		;;
+	(*)
+		printf "bulkrename: unknown command %s\n" "$1" >&2
+		exit 1
+		;;
+	esac
+done
diff --git a/trash b/trash
--- a/trash
+++ b/trash
@@ -2,34 +2,51 @@
 # trash: move files to trash
 # this file in public domain
 
+trashdir="${TRASH:-"${XDG_DATA_HOME:-"$HOME/.local/share"}/Trash"}"
+retval=0
+IFS="/"
+
 usage() {
 	echo "usage: trash file..." >&2
 	exit 1
 }
 
-# get trash directory to move file $1 into
-gettrash() {
-	mountfile="$(df "$1" | awk 'END {print $NF}')"
-	mounthome="$(df "$HOME" | awk 'END {print $NF}')"
-
-	if [ "$mountfile" != "$mounthome" ]
+# make trash directory and set its mode
+mktrashdir() {
+	if ! mkdir -p -- "$trashdir/files" "$trashdir/info" >/dev/null 2>&1
 	then
-		echo "$mountfile/.Trash-$UID"
-	else
-		echo ${TRASH:-$HOME/trash}
+		echo "trash: unable to create $trashdir"
+		exit 1
 	fi
-
+	chmod 700 "$trashdir"
 }
 
-# delete file with full path $1 into trash directory $2
-trash() {
-	basename=$(basename "$1")
-	body=${basename%.*}
-	ext=${basename##$body}
+# canonicalize "//", "/./", and "/../" from $filename into $path
+setpath() {
+	path=""
+	case "$filename" in
+	([!/]*) filename="$PWD/$filename" ;;
+	esac
+	for segment in $filename
+	do
+		case "$segment" in
+		("")                         ;;
+		(".")                        ;;
+		("..") path="${path%/*}"     ;;
+		(*)    path="$path/$segment" ;;
+		esac
+	done
+}
 
+# break basename of $path into body and extension; set $newfile
+# to "body.ext" (or "body_N.ext", for a unique file)
+setnewfile() {
+	basename="${path##*/}"
+	body="${basename%.*}"
+	ext="${basename##"$body"}"
 	i=""
 	p=""
-	while [ -e "$2/files/$body$p$i$ext" ]
+	while test -e "$trashdir/files/$body$p$i$ext"
 	do
 		p="_"
 		if [ -z "$i" ]
@@ -39,36 +56,43 @@ trash() {
 			i=$((i + 1))
 		fi
 	done
+	newfile="$body$p$i$ext"
+}
 
-	cat > "$2/info/$body$p$i$ext.trashinfo" <<END
-[Trash Info]
-Path=$1
-DeletionDate=$(date +"%FT%H:%M:%S")
-END
+# make $trashdir/info/$newfile.trashinfo file containing the original
+# path of the trashed file and its date of deletion
+mktrashinfo() {
+	cat > "$trashdir/info/$newfile.trashinfo" <<-END
+		[Trash Info]
+		Path=$path
+		DeletionDate=$(date +"%FT%H:%M:%S")
+	END
+}
 
-	mv "$1" "$2/files/$body$p$i$ext"
+# move $path into $trashdir/files/$newfile
+movetotrash() {
+
+	if ! mv -- "$path" "$trashdir/files/$newfile" >/dev/null 2>&1
+	then
+		echo "trash: $arg: could not move file to trash" >&2
+		retval=1
+	fi
 }
 
 [ $# -eq 0 ] && usage
-
-for f in "$@"; do
-
-	[ ! -e $f ] && echo "trash: $f: no such file or directory" >&2 && exit 1
-
-	trashdir="$(gettrash "$f")"
-	filename="$(readlink -f "$f")"
-
-	# create trash directory
-	if ! mkdir -p "$trashdir/files" "$trashdir/info"
+mktrashdir
+for arg
+do
+	filename="$arg"
+	setpath
+	if test ! -e "$path"
 	then
-		echo "trash: unable to create $trashdir"
-		exit 1
-	elif [ "$(ls -ld "$trashdir" | awk 'END {print $1}')" != 'drwx------' ]
-	then
-		chmod 700 "$trashdir"
+		echo "trash: $arg: no such file or directory" >&2
+		retval=1
+	else
+		setnewfile
+		mktrashinfo
+		movetotrash
 	fi
-
-	trash "$filename" "$trashdir"
 done
-
-exit 0
+exit $retval
diff --git a/untrash b/untrash
--- a/untrash
+++ b/untrash
@@ -2,70 +2,33 @@
 # untrash: restore files from trash
 # this file in public domain
 
-usage() {
-	echo "usage: trash file..." >&2
-	exit 1
-}
+ret=0
+for file
+do
+	basename="$(basename "$file")"
+	filesdir="$(dirname "$file")"
+	infofile="$filesdir/../info/$basename.trashinfo"
 
-# get info file of deleted file $2 in path $1
-getinfo() {
-	echo "$1/../info/$2.trashinfo"
-}
-
-# get original name of deleted file $2 on info file $1
-getorigfile() {
-	echo "$(cat $1 | awk -F= '/Path=/ {print $NF}')"
-}
-
-[ $# -eq 0 ] && usage
-
-for f in "$@"; do
-	if [ ! -e "$f" ]
+	if ! test -e "$file"
 	then
-		echo "trash: $f: no such file or directory" >&2
-		exit 1
-	fi
-
-	filename="$(readlink -f "$f")"
-	basename="$(basename "$f")"
-
-	# get directory of deleted files
-	filesdir="$(dirname "$filename")"
-	if [ "$(basename $filesdir)" != "files" ]
+		printf "trash: %s: no such file or directory\n" "$file" >&2
+		ret=1
+	elif ! test -f "$infofile"
 	then
-		echo "trash: $basename: file is not in trash" >&2
-		exit 1
-	fi
-
-	# get file containing information on deleted file
-	infofile="$(getinfo "$filesdir" "$basename")"
-	if [ ! -f "$infofile" ]
+		printf "trash: %s: cannot find original directory\n" "$basename" >&2
+		ret=1
+	elif origfile="$(awk -F= '/Path=/ {print $NF ; exit}' <"$infofile")" && test -e "$origfile"
 	then
-		echo "trash: $basename: cannot find original directory" >&2
-		exit 1
-	fi
-
-	# get original name of deleted file
-	origfile="$(getorigfile "$infofile" "$basename")"
-	if [ -e "$origfile" ]
+		printf "trash: %s: file already exists on original directory\n" "$basename" >&2
+		ret=1
+	elif ! mv -- "$file" "$origfile" 2>/dev/null
 	then
-		echo "trash: $basename: file already exists on original directory" >&2
-		exit 1
-	fi
-
-	# move deleted file to its original place
-	if ! mv "$filename" "$origfile"
+		printf "trash: %s: cannot move file to its original directory\n" "$basename" >&2
+		ret=1
+	elif ! rm -- "$infofile"
 	then
-		echo "trash: $basename: cannot move file to its original directory" >&2
-		exit 1
-	fi
-
-	# remove deleted file's information file
-	if ! rm "$infofile"
-	then
-		echo "trash: $basename: cannot clean file from trash" >&2
-		exit 1
+		printf "trash: %s: cannot clean file from trash\n" "$basename" >&2
+		ret=1
 	fi
 done
-
-exit 0
+exit "$ret"
